### ISSUE TITLE
how can I combine your project to understand the paper more deeply

### ISSUE THREAD

**Issue by wangyazhao001** [thustorage/max#1]
Hello，Xiaojian Liao！I  read your paper about Max:A Multicore-Accelerated File System for Flash Storage.To be honest, the ideas are really very creative,but it has a little difficult to understand it completely  for me. Can you give me some cints  how can I combine your project to understand the paper more deeply？

**Comment by liaoxiaojian** [comment]
@wangyazhao001 You can search `RPS`, `FILE_CELL `and `MLOG` in this repository to see the incremental implementation of Max atop F2FS. For more details see the macro definition in lines 14-19 of `Max/f2fs.h`.
